name: Build Atmosphere

on:
  workflow_dispatch: # 手动触发

jobs:
  build:
    runs-on: ubuntu-latest
    # 更换为 Switch 专用的 devkita64 镜像
    container: devkitpro/devkita64:latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive # 必须拉取所有子模块

      - name: Install dependencies and build
        shell: bash
        run: |
          # 更新源并安装依赖（包含 Python 2 和 lz4）
          (dkp-)pacman -Syu --noconfirm
          (dkp-)pacman -S --noconfirm switch-dev switch-libjpeg-turbo devkitARM devkitarm-rules python2 python-lz4
          
          # 配置环境
          export DEVKITPRO=/opt/devkitpro
          export DEVKITA64=$DEVKITPRO/devkitA64
          git config --global --add safe.directory "*"
          
          # 执行编译
          make -j$(nproc) dist

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: atmosphere-build
          path: atmosphere-*.zip # 上传 ZIP 整合包
